apiVersion: v1
kind: Service
metadata:
  name: spotlight-np
  namespace: spotlight
spec:
  type: NodePort
  selector:
    app: spotlight
    tier: frontend
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 31000
