apiVersion: v1
kind: Service
metadata:
  name: spotlight-lb
  namespace: spotlight
  labels:
    app: spotlight
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: spotlight
    tier: frontend
  ports:
    - name: server
      port: 8081
      targetPort: 80
