apiVersion: v1
kind: Pod
metadata:
  name: k8sspotlight
  namespace: spotlight
spec:
  containers:
    - name: k8sspotlight
      image: spotlightviz/spotlight:latest
      livenessProbe:
        httpGet:
          path: /probe/health
          port: 80
        initialDelaySeconds: 60
        periodSeconds: 30
