apiVersion: v1
kind: Service
metadata:
  name: spotlight-lb
  namespace: spotlight
spec:
  type: LoadBalancer
  selector:
    app: spotlight
    tier: frontend
  ports:
    - port: 8081
      targetPort: 80
